### PR TITLE
Builtin index

### PR DESCRIPTION
**Pull request by Dieterbe**

### CODE REVIEW

**Comment by Dieterbe** [comment]
requires https://github.com/dgryski/go-trigram/pull/16 and https://github.com/dgryski/go-trigram/issues/17

**Comment by Dieterbe** [comment]
@woodsaj any thoughts? if not i'll just go ahead.

here's the gist:
* this adresses #178, see that for benchmarks and such.
* should also remove the need to add ES metricdef query caching to graphite-raintank
* the index seems to be low overhead and quite responsive. artificial benchmarks show that data loads faster than through graphite+ES and using little resources, but we'll have to see how it behaves with a real workload in qa/prod.  the built-in index is not necessarily a great long term large-scale strategy and it's possible we'll yank the index stuff back out, it's not very tied in.
* pulled in some code from carbonapi/carbonmem/carbonserver, so i also added a LICENSE to deal with copyright, some of this code may later be moved to something like graphite-ng.
* end users aren't able to use the new graphite-endpoint yet until we can set up a datasource that sets the x-org-id header (there's no function support anyway)
* but for alerting we should be able to start using it soon. it bypasses a lot of graphite-api's issues (vague python stacktraces and such) and lower the load on ES .
* also comes with some cleanups for http, Req, defcache and a new output format for inspect-es to query the new endpoint


some showstoppers though:
* merging series together as in https://github.com/raintank/graphite-raintank/issues/13, should be easy to add this step to MT.
* grafana alert executor has sanity checks for the returned data and looks for timestamps the way data was originally saved. but we've since added logic to MT to quantize all timestamps. I think we can just remove this check from the executor and assume that the output returned by "graphite" (whether graphite-api or MT directly) is correct in that regard. i need to get the new raintank-docker working with the new stack though to implement this.

**Comment by woodsaj** [comment]
Go for it.

We will never give SaaS users access to be able to use this as an optional Datasource.  But as this matures we can add the necessary code to aplication stack that sits in front to authenticate then proxy users through.  

The X-ORG-ID header approach used with graphite was chosen as it was the simplest to implement given that graphite was never designed to be multi-tenant.

This tsdb is mult-tenant, so you can pass the "orgId" anyway you want.  I would suggest passing it either in the url path, "http://localhost:6060/<orgId>/render", or  in queryString params.

**Comment by Dieterbe** [comment]
the 2 todo's now live at
https://github.com/raintank/raintank-metric/issues/190
https://github.com/raintank/worldping-api/issues/37

**Pull request merged**
