### PR TITLE
use elasticsearch BulkAPI for indexing metricDefs

### PR DESCRIPTION
**Pull request by woodsaj**

### CODE REVIEW

**Comment by Dieterbe** [comment]
works for me in devstack.

but one thing to note is that now we lose track of whether messages get successfully indexed or not.

* for probe_events this would be a problem.
we could in theory monitor the `ErrorChannel` channel which contains the byte buffers to be flushed, from their we could work our way back to the nsq message id's (by either parsing the byte buffers, and keeping a mapping of metric id to nsq message id - quite hacky - or forking elastigo to maintain id's along with the binary data, and give us the id's back when it errors. or the other way around, feed all id's back that were part of successfull bulk flushes).
or a simple heuristic could just be to auto-ack all nsq messages after 30seconds or so, unless we see any error from the ErrorChannel. in that case, don't ack any nsq message from the timeframe leading up to that.  but we'd have to read the code to make sure the bulk indexer returns an error in time, if the http request takes a long time.

* for metrics, this might not be an issue ? @woodsaj is it? is it ok to skip metricdefs updates to ES once in a while? they'll sync up later?

**Comment by Dieterbe** [comment]
https://github.com/mattbaird/elastigo/issues/236

**Comment by woodsaj** [comment]
As the metric definitions are periodically updated, it is not a big problem if some metricDefs cant't be indexed, they will eventually succeed. Though it will be 5minutes before we try to index them again.

For events, this is more of a problem.
The BulkAPI returns all the necessary data needed.
https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html

However, the elastigo library does not use this data, and looking at the code doesnt even calculate the error count properly.  Additionally the  elastigo bulkApi implementation distributes documents among a pool of worker goroutines.  For events, i think we would be better of using a different implementation of the BulkAPI, even if we need to write that ourselves.

**Comment by Dieterbe** [comment]
interesting. individual commands can fail and they all have their own status listed in the response..
if we had the response returned, we could map the metric id's back to message id's that need to be acked, but I think there could still be edge cases where perhaps we've seen the same metric id from multiple nsq messages? so if we get a status 200 back for a given metric id, we may not be able to know which message it came from and ack the right one.  or does this problem not exist due to the redis caching? (which may also fail, of course)

**Comment by woodsaj** [comment]
for the metricDef use case, i think we can ACK the nsq messages as soon as we get them. We dont need strong guarantees that the messages will be persisted to elasticsearch.  If metrics dont make it into Elasticsearch, due to either elasticsearch problems or buffered messages being dropped due to application restarts, it is no big deal.

For nsq_metrics_to_elastic, i recommend
1) we just set `BulkIndexer.RetryForSeconds=N` so that if an error occurs while sending to Elasticsearch, the request will be retried in N seconds.
2) use the ErrorChannel to increment the metricsToEsFail statsD counter


Given that we need strong guarantees that the events get persisted to Elastic for nsq_probe_events_to_elastic, we cant use the async BulkIndexer provided by elastigo.  For this case, we need to use a different lib or role our own elastic (shouldnt be hard as the only request made is to `POST /_bulk').  We would then need to buffer nsq messages and periodically flush to elastic, using the response to identify which messages failed and re-queue them.  Only after failed messages have been re-queued can we ACK the nsq messages.

**Comment by woodsaj** [comment]
for handling the errors, the BulkIndexer allows a customer "Sender" to be set to replace the default (this is primarily used to support unitTests)
https://github.com/mattbaird/elastigo/blob/master/lib/corebulk.go#L48


So we could easily replace the default https://github.com/mattbaird/elastigo/blob/master/lib/corebulk.go#L330  with our own sender that correctly handles the errors.

**Comment by Dieterbe** [comment]
> Only after failed messages have been re-queued can we ACK the nsq messages.

i would only ack the message to nsqd once we get confirmation all contents of the message (currently 1 event per msg, later probably more) have been indexed successfully.
i don't understand why we would ack to nsqd just after re-queueing (you mean re-queueing in the bulk indexer right?) because that operation might fail again.

> we could easily replace the default with our own sender that correctly handles the errors.

this looks like an elegant approach

**Comment by woodsaj** [comment]
>i don't understand why we would ack to nsqd just after re-queueing
NSQ performance will degrade if we delay ACK'ing messages.  So if a write to Elastic fails it would be better to re-queue just the failed events in a new NSQ message, rather then try again and delay the ACKing of NSQ messages.

**Comment by Dieterbe** [comment]
testing with mariadb-1 and mariadb-2 using the bulkindexer and mariadb-3 stuck to master, show that for roughly the same cpu consumption : 
* bulkindexer receive and handle around 38 messages/s, with an es_put_duration (time to send index commands for all metrics in the nsq message) of about 2ms each
* master around 3/s with more variability, with es_put_duration of about 2ms each as well, but it occassionally spikes to 8s (i.e. only mariadb-3 shows the spikes)

**Pull request merged**
